// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArcUAsZ3IiKBmshGCSHdmZyQ92gZFepHk',
    appId: '1:154850396192:web:0ac71e07087bec291d9445',
    messagingSenderId: '154850396192',
    projectId: 'fooddeliveryapp-ac2f1',
    authDomain: 'fooddeliveryapp-ac2f1.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-ac2f1.appspot.com',
    measurementId: 'G-718DVYVDN6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5LX6uBNmsNO56O4dQJSzHuO0nQgz7NdI',
    appId: '1:154850396192:android:f1a9b3c273b46cd51d9445',
    messagingSenderId: '154850396192',
    projectId: 'fooddeliveryapp-ac2f1',
    storageBucket: 'fooddeliveryapp-ac2f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPTWAsfTY1cSqFYDRMbw_3dwESnhJbnM0',
    appId: '1:154850396192:ios:77a7418551375a7c1d9445',
    messagingSenderId: '154850396192',
    projectId: 'fooddeliveryapp-ac2f1',
    storageBucket: 'fooddeliveryapp-ac2f1.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPTWAsfTY1cSqFYDRMbw_3dwESnhJbnM0',
    appId: '1:154850396192:ios:792bc7ca2d083fa51d9445',
    messagingSenderId: '154850396192',
    projectId: 'fooddeliveryapp-ac2f1',
    storageBucket: 'fooddeliveryapp-ac2f1.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
